export const itemIcons: Record<string, string> = {
	Honey: "🍯",
	Treat: "🍪",
	Strawberry: "🍓",
	Blueberry: "🫐",
	Bamboo: "🎋",
	Seed: "🌱",
	"Pine Cone": "🌲",
	"Royal Jelly": "🧴",
	"Lunar Treat": "🌙",
	"Lunar Essence": "🌙",
	"Fire Essence": "🔥",
	"Water Essence": "💧",
	"Wind Essence": "💨",
	"Lunar Shard": "💎",
	Starflower: "⭐",
	Dice: "🎲",
	"Double Dice": "🎲",
	"Triple Dice": "🎲",
	Glitter: "✨",
	"Moon Extract": "🌙",
	"Strawberry Extract": "🍓",
	"Blueberry Extract": "🫐",
	"Seed Oil": "🌻",
	"Bamboo Flask": "🎋",
	"Magic Carrot": "🥕",
	"Golden Carrot": "🥕",
	"Golden Apple": "🍎",
	"Apple Treat": "🍎",
	"Carrot Treat": "🥕",
	"Pot'O'Vegetation": "🌿",
	"Foaming Carrot Juice": "🥕",
	"Rich Apple Juice": "🍎",
	"Exp Essence": "🟢",
	"Singularity Essence": "🌀",
	"Shiny Jelly": "💫",
	"Gardener's Bundle": "🪴",
	Ticket: "🎟️",
	"Gold Egg": "🥚",
	"Diamond Egg": "💎",

	Shovel: "🛠️",
	Rake: "🛠️",
	Hammer: "🔨",
	Magnet: "🧲",
	Scissors: "✂️",
	Scythe: "🗡️",
	Axe: "🪓",
	Pickaxe: "⛏️",
	"Gold Magnet": "🧲",
	"Honey Dipper": "🍯",
	"Fire Scythe": "🔥",
	"Snow Shovel": "❄️",
	"Windy Staff": "💨",
	"Bamboo Spear": "🎋",
	"Bamboo Rake": "🎋",
	"Bamboo Staff": "🎋",
	"Nature Staff": "🌿",

	Satchel: "🎒",
	Jar: "🫙",
	Flask: "🧪",
	Backpack: "🎒",
	"Flower Pot": "🪴",
	"Bouquet Of Flowers": "💐",
	Cauldron: "🧪",
	Hive: "🐝",
	Furnace: "🔥",
	"Coal Basket": "🧺",
	Fridge: "🧊",
	"Ice Basket": "🧺",
	"Sheaf of Bamboo": "🎋",
	"Blossom Canister": "🌸",
	"Seed Pouch": "🌱",

	"Bronze Hydrant": "🚰",
	"Silver Hydrant": "🚰",
	"Golden Hydrant": "🚰",
	"Diamond Hydrant": "🚰",
	"Emerald Hydrant": "🚰",

	"Fire Planter": "🪴",
	"Ice Planter": "🪴",
	"Cardboard Planter": "🪴",
	"Sticker Planter": "🪴",
};

export function getItemIcon(item: string): string {
	return itemIcons[item] ?? "🐝";
}
